version: 0.2

phases:

  install:
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's symlink our 
      # application source code into that directory structure.
      - mkdir -p /go/src/github.com/dcb9 ; ln -s "${CODEBUILD_SRC_DIR}" "/go/src/github.com/dcb9/keymeshOAuth"

      # Install golint
      - go get -u github.com/golang/lint/golint

  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/github.com/dcb9/keymeshOAuth"

      # Fetch all dependencies
      - go get ./...

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Check for common Go application problems with 'go tool vet'
      - go tool vet .

      # Run all tests included with our application
      - go test ./...

  build:
    commands:

      # Build our go application
      - go build -o main

      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
